# Generated by Django 5.1.4 on 2024-12-17 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='total_income',
            new_name='max_budget_amount',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='recurring_cycle_end',
            new_name='month',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='recurring',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='total_savings',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savinggoal',
            name='budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='ExtraIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_received', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
