# Generated by Django 5.1.4 on 2024-12-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_rename_total_income_budget_max_budget_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('fixed', 'Pago Fijo'), ('leisure', 'Ocio y Entretenimiento'), ('other', 'Otros'), ('savings', 'Ahorro')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savinggoal',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
